# Generated by Django 5.2.7 on 2026-02-04 16:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("RESTAURANT", "Restaurant"),
                            ("NGO", "NGO"),
                            ("VOLUNTEER", "Volunteer"),
                        ],
                        default="ADMIN",
                        max_length=10,
                    ),
                ),
                (
                    "must_change_password",
                    models.BooleanField(
                        default=False,
                        help_text="Force user to change password on next login",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "icon_url",
                    models.CharField(
                        blank=True,
                        help_text="URL or emoji for badge icon",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="NGOProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="ngo_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ngo_name",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_name",
                                message="This field can only contain alphabetic characters and spaces.",
                                regex="^[a-zA-Z\\s]+$",
                            )
                        ],
                    ),
                ),
                ("registration_number", models.CharField(max_length=100, unique=True)),
                ("address", models.TextField()),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "contact_number",
                    models.CharField(
                        help_text="10-digit mobile number",
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_contact_number",
                                message="Contact number must be exactly 10 digits.",
                                regex="^\\d{10}$",
                            )
                        ],
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/ngos/"
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="banner_images/ngos/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RestaurantProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="restaurant_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant_name",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_name",
                                message="This field can only contain alphabetic characters and spaces.",
                                regex="^[a-zA-Z\\s]+$",
                            )
                        ],
                    ),
                ),
                ("address", models.TextField()),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/restaurants/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DonationCamp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location_address", models.TextField()),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("start_time", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ngo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="camps",
                        to="portal.ngoprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VolunteerProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="volunteer_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_name",
                                message="This field can only contain alphabetic characters and spaces.",
                                regex="^[a-zA-Z\\s]+$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                (
                    "aadhar_number",
                    models.CharField(
                        blank=True,
                        help_text="12-digit Aadhar number",
                        max_length=12,
                        null=True,
                        unique=True,
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "skills",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Driving, Cooking, Medical",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "last_location_update",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last geolocation update",
                        null=True,
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/volunteers/"
                    ),
                ),
                (
                    "webpush_subscription",
                    models.TextField(
                        blank=True,
                        help_text="Web push subscription data (JSON)",
                        null=True,
                    ),
                ),
                (
                    "allow_location_sharing",
                    models.BooleanField(
                        default=True,
                        help_text="Allow real-time location sharing during active tasks",
                    ),
                ),
                (
                    "share_location_with_ngos",
                    models.BooleanField(
                        default=True,
                        help_text="Allow NGOs to see my real-time location",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registered_ngo",
                    models.ForeignKey(
                        blank=True,
                        help_text="NGO that registered this volunteer",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_volunteers",
                        to="portal.ngoprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NGOVolunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "ngo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.ngoprofile",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.volunteerprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("ngo", "volunteer")},
            },
        ),
        migrations.AddField(
            model_name="ngoprofile",
            name="volunteers",
            field=models.ManyToManyField(
                related_name="registered_ngos",
                through="portal.NGOVolunteer",
                to="portal.volunteerprofile",
            ),
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food_description",
                    models.CharField(
                        help_text="e.g., 20 veg thalis, 5kg rice", max_length=255
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="e.g., number of meals, weight in kg"
                    ),
                ),
                ("pickup_address", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Pickup"),
                            ("ACCEPTED", "On its Way"),
                            ("COLLECTED", "Collected by Volunteer"),
                            ("VERIFICATION_PENDING", "Pending Verification"),
                            ("DELIVERED", "Delivered & Verified"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("collected_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1 Star"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ],
                        help_text="Rating from 1 to 5 stars",
                        null=True,
                    ),
                ),
                (
                    "review",
                    models.TextField(
                        blank=True,
                        help_text="NGO's review of the volunteer delivery",
                        null=True,
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When NGO verified the donation",
                        null=True,
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(
                        blank=True, help_text="NGO's verification notes", null=True
                    ),
                ),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                (
                    "verification_count",
                    models.IntegerField(
                        default=0, help_text="Number of attempts before verification"
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_donations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_camp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donations_received",
                        to="portal.donationcamp",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="portal.restaurantprofile",
                    ),
                ),
                (
                    "assigned_volunteer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_donations",
                        to="portal.volunteerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VolunteerBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_awarded", models.DateTimeField(auto_now_add=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.badge"
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to="portal.volunteerprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("volunteer", "badge")},
            },
        ),
    ]
