# Generated by Django 5.2.7 on 2026-02-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngoprofile',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='ngo_darpan_id',
            field=models.CharField(blank=True, help_text='Unique NGO Darpan ID', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='registration_doc',
            field=models.FileField(blank=True, help_text='Official Registration Certificate', null=True, upload_to='ngo_docs/'),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='fssai_number',
            field=models.CharField(blank=True, help_text='14-digit FSSAI License Number', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='verification_status',
            field=models.CharField(choices=[('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Overall verification status of the user'),
        ),
    ]
