# Generated by Django 5.2.7 on 2026-02-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_ngoprofile_registration_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngoprofile',
            name='registration_doc',
        ),
    ]
