# Generated by Django 5.2.7 on 2026-02-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_ngoprofile_registration_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/restaurants/'),
        ),
    ]
